---
abstract: 'Search and browse Mini CPAN'
author:
  - 'Leon Brocard <acme@astray.com>'
  - 'Christian Walde <walde.christian@googlemail.com>'
build_requires:
  CGI: 3.16
  Capture::Tiny: 0
  Compress::Zlib: 0
  Exporter: 0
  File::Find: 0
  File::Path: 0
  File::Slurp: 0
  File::Temp: 0
  HTTP::Response: 0
  Test::Builder: 0
  Test::InDistDir: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300001, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CPAN-Mini-Webserver
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  CPAN::Mini::Webserver:
    file: lib/CPAN/Mini/Webserver.pm
    version: 0.56
  CPAN::Mini::Webserver::Index:
    file: lib/CPAN/Mini/Webserver/Index.pm
    version: 0.56
  CPAN::Mini::Webserver::Templates:
    file: lib/CPAN/Mini/Webserver/Templates.pm
    version: 0.56
  CPAN::Mini::Webserver::Templates::CSS:
    file: lib/CPAN/Mini/Webserver/Templates/CSS.pm
    version: 0.56
  CPAN::Mini::Webserver::Templates::Images:
    file: lib/CPAN/Mini/Webserver/Templates/Images.pm
    version: 0.56
requires:
  App::Cache: 0
  Archive::Peek: 0.33
  CPAN: 0
  CPAN::Mini::App: 0.565
  Encode: 0
  File::Spec::Functions: 0
  File::Type: 0
  Getopt::Long: 0
  HTTP::Server::Simple: 0.34
  HTTP::Server::Simple::CGI: 0
  Lingua::StopWords: 0
  List::MoreUtils: 0
  MIME::Base64: 0
  Module::InstalledVersion: 0
  Moose: 0
  PPI: 0
  PPI::HTML: 0
  Parse::CPAN::Authors: 0
  Parse::CPAN::Meta: 0
  Parse::CPAN::Packages: 2.35
  Parse::CPAN::Whois: 0.02
  Path::Class: 0
  Pod::Simple::HTML: 0
  Pod::Simple::Text: 0
  Safe: 0
  Search::QueryParser: 0
  Search::Tokenizer: 0
  String::CamelCase: 0
  Template::Declare: 0
  Template::Declare::Tags: 0.29
  Text::Unidecode: 0
  Try::Tiny: 0
  base: 0
  perl: 5.008
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=CPAN-Mini-Webserver
  homepage: https://github.com/wchristian/cpan-mini-webserver
  repository: https://github.com/wchristian/cpan-mini-webserver.git
version: 0.56
