--- #YAML:1.0
name:                CPAN-Mini-Webserver
version:             0.32
abstract:            ~
license:             perl
author:              
    - Leon Brocard <acme@astray.com>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    App::Cache:                    0
    Convert::UU:                   0
    CPAN::Mini:                    0
    HTTP::Server::Simple::CGI:     0
    IO::Capture::Stdout:           0
    Moose:                         0
    Parse::CPAN::Authors:          0
    Parse::CPAN::Packages:         0
    Path::Class:                   0
    Perl6::Say:                    0
    Pod::Simple::HTML:             0
    PPI:                           0
    PPI::HTML:                     0
    Template::Declare:             0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
