---
abstract: 'Search and browse Mini CPAN'
author:
  - 'Leon Brocard <acme@astray.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.59, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CPAN-Mini-Webserver
no_index:
  directory:
    - t
    - inc
requires:
  App::Cache: 0
  Archive::Peek: 0.33
  CGI: 3.16
  CPAN::Mini: 0.565
  Capture::Tiny: 0
  Compress::Zlib: 0
  Cwd: 0
  File::Path: 0
  File::Slurp: 0
  File::Type: 0
  HTTP::Server::Simple: 0.34
  List::MoreUtils: 0
  MIME::Base64: 0
  Module::InstalledVersion: 0
  Moose: 0
  PPI: 0
  PPI::HTML: 0
  Parse::CPAN::Authors: 0
  Parse::CPAN::Meta: 0
  Parse::CPAN::Packages: 2.35
  Parse::CPAN::Whois: 0.02
  Path::Class: 0
  Pod::Simple::HTML: 0
  Search::QueryParser: 0
  Search::Tokenizer: 0
  String::CamelCase: 0
  Template::Declare: 0.29
  Test::InDistDir: 0
  Test::More: 0
  Text::Unidecode: 0
version: 0.55
